if(MORU_TEST)
enable_testing()
include(GoogleTest)

add_executable(test_hello test/rng.cpp)
target_sources(
    test_hello
        PRIVATE
            ${MORU_src}
)
target_include_directories(
    test_hello
        PRIVATE
            ${MORU_INCLUDE_DIR}
)
target_link_libraries(
    test_hello
        PRIVATE
            ${MORU_LINK_LIBRARY}
            GTest::gtest_main
)
target_compile_features(
    test_hello
        PRIVATE
            cxx_std_20
)
target_compile_options(
    test_hello
        PRIVATE
            ${MORU_COMPILE_OPTION}
)
set_target_properties(
    test_hello
        PROPERTIES
            ${MORU_PROPERTY}
)

gtest_discover_tests(test_hello)
endif()
